name: "Express Approval Workflow"
description: "Fast-track approval workflow with skip options for urgent items"

states:
  - name: "draft"
    type: "initial"
  - name: "priority_review"
    type: "approval"
  - name: "standard_review"
    type: "approval"
  - name: "final_review"
    type: "approval"
  - name: "completed"
    type: "terminal"
  - name: "cancelled"
    type: "terminal"
  - name: "escalated"
    type: "special"

transitions:
  - from: "draft"
    to: "priority_review"
    action: "submit"
    condition: "is_urgent"
  - from: "draft"
    to: "standard_review"
    action: "submit"
    condition: "is_normal"
  - from: "priority_review"
    to: "final_review"
    action: "approve"
    condition: "urgent_fast_track"
  - from: "priority_review"
    to: "standard_review"
    action: "approve"
    condition: "standard_process"
  - from: "standard_review"
    to: "final_review"
    action: "approve"
  - from: "final_review"
    to: "completed"
    action: "approve"
  - from: "priority_review"
    to: "draft"
    action: "reject"
  - from: "standard_review"
    to: "draft"
    action: "reject"
  - from: "final_review"
    to: "standard_review"
    action: "reject"
  - from: "*"
    to: "escalated"
    action: "escalate"
    condition: "timeout_exceeded"
  - from: "escalated"
    to: "final_review"
    action: "approve"
  - from: "*"
    to: "cancelled"
    action: "cancel"

approval_rules:
  min_approvals: 2
  allow_self_approval: false
  escalation_timeout_hours: 24
  urgent_timeout_hours: 12
  skip_levels_allowed: true
  escalation_required_after_timeout: true