# Aviation Workflow System - Configuration
# This file defines module configurations, default data, and system settings

# Application Configuration
app:
  name: "Aviation Workflow System"
  version: "1.0.0"
  environment: "development"
  debug: true

# Database Configuration
database:
  url: "sqlite:///./workflow.db"
  echo_sql: false
  pool_size: 10
  max_overflow: 20

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  prefix: "/api"
  version: "v1"
  cors_origins:
    - "http://localhost:8501"
    - "http://localhost:3000"
  cors_methods:
    - "GET"
    - "POST" 
    - "PUT"
    - "DELETE"
    - "OPTIONS"

# Streamlit Configuration
streamlit:
  host: "0.0.0.0"
  port: 8501
  server_headless: true
  browser_gather_usage_stats: false

# Module Configuration
modules:
  # Core modules that should be enabled
  enabled_modules:
    - "departments"
    - "templates"
    - "comments"
    - "approvals"
  
  # Module-specific configurations
  departments:
    enabled: true
    auto_create_defaults: true
    default_departments:
      - name: "flight_operations"
        display_name: "Flight Operations"
        description: "Manages flight planning, crew scheduling, and operational oversight"
        manager: "Captain Sarah Mitchell"
        contact_email: "flight.ops@aviation.com"
        phone: "+1-555-0101"
        location: "Operations Center, Building A"
      
      - name: "maintenance"
        display_name: "Aircraft Maintenance"
        description: "Responsible for aircraft maintenance, inspections, and airworthiness"
        manager: "Chief Engineer Robert Chen"
        contact_email: "maintenance@aviation.com"
        phone: "+1-555-0102"
        location: "Maintenance Hangar, Building C"
      
      - name: "safety_quality"
        display_name: "Safety & Quality Assurance"
        description: "Ensures safety compliance, quality standards, and regulatory adherence"
        manager: "Safety Director Maria Rodriguez"
        contact_email: "safety@aviation.com"
        phone: "+1-555-0103"
        location: "Safety Office, Building B"
      
      - name: "ground_services"
        display_name: "Ground Services"
        description: "Handles baggage, cargo, fueling, and ground support operations"
        manager: "Ground Supervisor James Wilson"
        contact_email: "ground@aviation.com"
        phone: "+1-555-0104"
        location: "Ground Operations, Terminal 1"
      
      - name: "customer_service"
        display_name: "Customer Service"
        description: "Manages passenger services, complaints, and customer experience"
        manager: "Service Director Lisa Thompson"
        contact_email: "service@aviation.com"
        phone: "+1-555-0105"
        location: "Customer Service Center, Terminal 2"

  templates:
    enabled: true
    auto_create_defaults: true
    default_templates:
      - name: "aircraft_maintenance_workflow"
        display_name: "Aircraft Maintenance Workflow"
        description: "Standard workflow for aircraft maintenance requests and approvals"
        department_sequence:
          - "maintenance"
          - "safety_quality"
          - "flight_operations"
        approval_rules:
          require_comment: true
          min_approvals: 2
          allow_parallel_approval: false
          escalation_hours: 24
        workflow_config:
          timeout: 7200  # 2 hours
          auto_approve_minor: false
          require_supervisor_approval: true
        category: "maintenance"
        is_active: true
      
      - name: "safety_incident_workflow"
        display_name: "Safety Incident Reporting"
        description: "Workflow for processing safety incidents and corrective actions"
        department_sequence:
          - "safety_quality"
          - "flight_operations"
          - "maintenance"
        approval_rules:
          require_comment: true
          min_approvals: 1
          allow_parallel_approval: true
          escalation_hours: 4
        workflow_config:
          timeout: 3600  # 1 hour
          auto_approve_minor: false
          require_supervisor_approval: true
          priority: "high"
        category: "safety"
        is_active: true
      
      - name: "customer_complaint_workflow"
        display_name: "Customer Complaint Resolution"
        description: "Standard process for handling customer complaints and feedback"
        department_sequence:
          - "customer_service"
          - "ground_services"
        approval_rules:
          require_comment: false
          min_approvals: 1
          allow_parallel_approval: true
          escalation_hours: 48
        workflow_config:
          timeout: 14400  # 4 hours
          auto_approve_minor: true
          require_supervisor_approval: false
        category: "customer_service"
        is_active: true

  comments:
    enabled: true
    allow_anonymous: false
    require_approval: false
    max_length: 5000
    allow_attachments: false

  approvals:
    enabled: true
    require_comment: false
    allow_skip: false
    auto_escalate: true
    escalation_hours: 24
    allow_parallel: true
    max_rejections: 3

# Workflow Engine Configuration
workflow:
  engine: "burr"
  state_storage: "local"
  state_directory: "./burr_state"
  auto_save: true
  save_interval: 300  # 5 minutes
  
  # Default workflow settings
  defaults:
    timeout: 3600  # 1 hour
    max_steps: 10
    allow_rollback: true
    require_comments: false

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  handlers:
    - type: "console"
    - type: "file"
      filename: "logs/aviation_workflow.log"
      max_bytes: 10485760  # 10MB
      backup_count: 5

# Security Configuration
security:
  secret_key: "dev-secret-key-change-in-production"
  algorithm: "HS256"
  access_token_expire_minutes: 30
  
  # CORS settings
  allow_credentials: true
  allow_methods: ["*"]
  allow_headers: ["*"]

# Feature Flags
features:
  enable_auth: false
  enable_file_uploads: false
  enable_notifications: false
  enable_audit_log: false
  enable_metrics: true
  enable_caching: false

# Cache Configuration (if enabled)
cache:
  type: "memory"  # memory, redis
  ttl: 300  # 5 minutes
  max_size: 1000

# Redis Configuration (if used)
redis:
  enabled: false
  url: "redis://localhost:6379/0"
  connection_pool_size: 10
  decode_responses: true

# Development Configuration
development:
  reload: true
  debug_routes: true
  show_docs: true
  cors_allow_all: true
  mock_auth: true
  seed_data: true

# Production Configuration (override for production)
production:
  debug: false
  reload: false
  show_docs: false
  cors_allow_all: false
  mock_auth: false
  seed_data: false
  
  # Production database
  database:
    url: "postgresql://user:password@localhost:5432/aviation_workflow"
    ssl_mode: "require"
    
  # Production logging
  logging:
    level: "WARNING"
    handlers:
      - type: "file"
        filename: "/var/log/aviation_workflow.log"

# Testing Configuration
testing:
  database:
    url: "sqlite:///:memory:"
  
  modules:
    enabled_modules:
      - "departments"
      - "templates"
  
  features:
    enable_auth: false
    seed_data: true

# Monitoring Configuration
monitoring:
  health_check_interval: 30
  metrics_enabled: true
  performance_tracking: true
  error_reporting: true

# Backup Configuration
backup:
  enabled: false
  interval: "daily"
  retention_days: 30
  storage_path: "./backups"

# Integration Configuration
integrations:
  # External systems (future)
  external_apis: {}
  
  # Notification services (future)
  notifications:
    email:
      enabled: false
    slack:
      enabled: false

# Custom Aviation Settings
aviation:
  # Aircraft registration patterns
  aircraft_tail_patterns:
    - "N[0-9]{1,5}[A-Z]{1,3}"  # US registration
    - "C-[A-Z]{4}"             # Canadian registration
  
  # Airport codes
  default_airports:
    - "KORD"  # Chicago O'Hare
    - "KLAX"  # Los Angeles
    - "KJFK"  # New York JFK
    - "KATL"  # Atlanta
    - "KDEN"  # Denver
    - "KIAH"  # Houston
    - "KPHX"  # Phoenix
  
  # Maintenance types
  maintenance_types:
    - "Routine"
    - "Scheduled"
    - "Unscheduled"
    - "Emergency"
    - "Inspection"
    - "Repair"
    - "Modification"
  
  # Priority levels
  priority_levels:
    - name: "low"
      color: "#28a745"
      escalation_hours: 72
    - name: "medium"
      color: "#ffc107"
      escalation_hours: 24
    - name: "high"
      color: "#fd7e14"
      escalation_hours: 8
    - name: "critical"
      color: "#dc3545"
      escalation_hours: 2